/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195148564
**********************/

 SELECT 'test21DoubleBlockWithScriptDelimiter.csv' "FILE1" FROM DUAL 
/

 SELECT 'test21DoubleBlockWithScriptDelimiter.csv' "FILE2" FROM DUAL 
/

 SELECT 'test21DoubleBlockWithScriptDelimiter.csv' "FILE3" FROM DUAL 
/

