/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195147748
**********************/

SELECT LEVEL COL1,  1 / 0  "MY_COLUMN" , 'my creazy long text' COL3, 0 COL4  FROM DUAL CONNECT BY LEVEL <=    100