/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195147963
**********************/


-- my obstructive comment ; * / 
 SELECT 'test023SingleBlockWithSingleLineCommentBeforeAndAfter.csv' "MY_ROW2" FROM DUAL 
-- my obstructive comment ; * / 