/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195146968
**********************/


-- my obstructive comment ; * / 
 SELECT 'test022SingleBlockWithSingleLineCommentBefore.csv' "MY_ROW2" FROM DUAL 