/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195146520
**********************/

 SELECT 'test11SingleBlockWithScriptDelimiter.csv' "MY_ROW2" FROM DUAL 
/