/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195147377
**********************/

/* 123 


 234my obstructive comment ; */  SELECT 'test03SingleBlockWithMultilineLineCommentBeforeAndAfter.csv' "MY_ROW1" FROM DUAL /* 123 


 234my obstructive comment ; */ 