/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195147566
**********************/

 SELECT 'test12SingleBlockWithScriptDelimiterAndEmptyLines.csv' "MY_ROW2" FROM DUAL 
/

