/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195148159
**********************/

 SELECT 'test01SingleBlock.csv' "MY_ROW" FROM DUAL 