/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195146785
**********************/

 SELECT 'test021SingleBlockWithSingleLineCommentAfter.csv' "MY_ROW" FROM DUAL 
-- my obstructive comment ; * / 