/********************* 
Autogenerated
	from: com.capgemini.fitnesseplugin.db.ExportSqlResultSetBlockTest
	date: 20160424195148371
**********************/

 SELECT 'test13SingleBlockWithDoubleScriptDelimiterAndEmptyLines.csv' "MY_ROW2" FROM DUAL 
/


/

